Repository minos-framework/minos-discovery, pull requests merged in 2021-08, with the labels that each got.

#40 Refactor endpoints - issue #31
  minos/api_gateway/discovery/__init__.py
  minos/api_gateway/discovery/__main__.py
  minos/api_gateway/discovery/cli.py
  minos/api_gateway/discovery/database/client.py
  minos/api_gateway/discovery/handlers.py
  minos/api_gateway/discovery/health_status/checkers.py
  minos/api_gateway/discovery/health_status/services.py
  minos/api_gateway/discovery/launchers.py
  minos/api_gateway/discovery/service.py
  poetry.lock
  tests/config.yml
  tests/test_api_gateway/test_discovery/test_cli.py
  tests/test_api_gateway/test_discovery/test_handlers.py
  tests/test_api_gateway/test_discovery/test_service.py
Labels: refactor

#49 Migrate to `aioredis` - issue #42
  minos/api_gateway/discovery/database/client.py
  minos/api_gateway/discovery/domain/microservice.py
  minos/api_gateway/discovery/health_status/checkers.py
  minos/api_gateway/discovery/views/endpoint.py
  minos/api_gateway/discovery/views/microservice.py
  poetry.lock
  pyproject.toml
  tests/test_api_gateway/test_discovery/test_database/test_client.py
  tests/test_api_gateway/test_discovery/test_periodic/test_abc.py
  tests/test_discovery.py
  tests/test_handlers_config.yml
Labels: enhancement, refactor

#51 Create connection pool - issue #43
  minos/api_gateway/discovery/database/client.py
  minos/api_gateway/discovery/service.py
  minos/api_gateway/discovery/views/endpoint.py
  minos/api_gateway/discovery/views/microservice.py
Labels: enhancement

#53 Endpoint pattern matching - issue #52
  minos/api_gateway/discovery/domain/endpoint.py
  minos/api_gateway/discovery/domain/microservice.py
  minos/api_gateway/discovery/views/endpoint.py
  poetry.lock
  tests/test_api_gateway/test_discovery/test_views/test_endpoint.py
Labels: enhancement

#59 Adapt system helath - issue #50
  minos/api_gateway/discovery/domain/microservice.py
  minos/api_gateway/discovery/health_status/checkers.py
  tests/test_api_gateway/test_discovery/test_periodic/test_abc.py
Labels: enhancement

#55 Add verb - issue #54
  minos/api_gateway/discovery/database/client.py
  minos/api_gateway/discovery/domain/__init__.py
  minos/api_gateway/discovery/domain/endpoint.py
  minos/api_gateway/discovery/domain/exceptions.py
  minos/api_gateway/discovery/domain/microservice.py
  minos/api_gateway/discovery/views/endpoint.py
  tests/test_api_gateway/test_discovery/test_views/test_endpoint.py
  tests/test_api_gateway/test_discovery/test_views/test_microservice.py
Labels: enhancement

#57 Refactor db structure - issue #56
  minos/api_gateway/discovery/domain/microservice.py
  minos/api_gateway/discovery/views/endpoint.py
Labels: enhancement, refactor

#63 #62 (integrate with `microservices` and `api-gateway`)
  minos/api_gateway/discovery/database/client.py
  minos/api_gateway/discovery/domain/endpoint.py
  minos/api_gateway/discovery/domain/microservice.py
  minos/api_gateway/discovery/health_status/checkers.py
  poetry.lock
  tests/config.yml
  tests/test_api_gateway/test_discovery/test_periodic/test_abc.py
  tests/test_api_gateway/test_discovery/test_periodic/test_service.py
Labels: enhancement
