Repository minos-framework/minos-discovery, pull requests merged in 2021-05, with the labels that each got.

#9 #7 (update `.gitignore`)
  .gitignore
  tests/test_discovery.py
Labels: meta

#12 Update api_gateway_common
  minos/api_gateway/discovery/periodic/abc.py
  poetry.lock
  pyproject.toml
  tests/test_api_gateway/test_discovery/test_periodic/test_service.py
Labels: enhancement

#15 Replace web.Response to web.json_response
  minos/api_gateway/discovery/handlers.py
  tests/test_api_gateway/test_discovery/test_periodic/test_abc.py
Labels: bug

#19 #18 - First version of docs
  CONTRIBUTING.md
  Makefile
  README.md
  RUNTHETESTS.md
  SETUP.md
  docs/Makefile
  docs/api/modules.rst
  docs/authors.rst
  docs/conf.py
  docs/history.rst
  docs/index.rst
  docs/make.bat
  docs/readme.rst
  docs/runthetests.rst
  docs/usage.rst
  poetry.lock
  pyproject.toml
Labels: documentation
