Repository minos-framework/minos-discovery, pull requests merged in 2022-02, with the labels that each got.

#76 0.1.0
  .gitignore
  HISTORY.md
  minos/api_gateway/discovery/__init__.py
  minos/api_gateway/discovery/database/client.py
  minos/api_gateway/discovery/domain/microservice.py
  minos/api_gateway/discovery/views/__init__.py
  minos/api_gateway/discovery/views/endpoints.py
  pyproject.toml
  tests/test_api_gateway/test_discovery/test_views/test_endpoints.py
Labels: release

#79 #70 increase redis pool conn
  minos/api_gateway/discovery/database/client.py
Labels: enhancement

#81 #78 - Subscription wrong IP
  minos/api_gateway/discovery/database/client.py
  minos/api_gateway/discovery/domain/microservice.py
  poetry.lock
  pyproject.toml
  tests/test_api_gateway/test_discovery/test_database/test_client.py
  tests/test_api_gateway/test_discovery/test_periodic/test_abc.py
  tests/test_api_gateway/test_discovery/test_views/test_microservice.py
Labels: bug
